Setup Leaderbord - webpack
GintsM/Leaderboard pull request #1
Opened 2021-11-16 13:18 UTC by GintsM

### In the project I use
 * Gitflow - development branch is for development and main for production
 * Webpack
 * Plain HTML and minimal CSS to style
 * ES 6 modules to import and export

2021-11-16 13:27 UTC, od-c0d3r requested changes
Asslam Alikom @GintsM  

Hi 👋🏽, While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't fulfill one of the project `General Requirements` :
-  Make sure that you documented your work in a professional way. [LINK](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/m1_basic_structure.md#:~:text=make%20sure%20that%20you%20documented%20your%20work%20in%20a%20professional%20way.)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2021-11-16 20:24 UTC, GzimAsani requested changes
# Hi @GintsM                          
Good job so far! Your code looks fine, good job :+1:  :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good PR description :clap: 

## Required Changes ♻️ 
- [ ] Please be reminded  for next projects that the changes should be asked to be merged from the feature bracn to the master branch
- [ ] _Check inline comments for more information :arrow_double_down:_ 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-16 20:24 UTC, GzimAsani commented on README.md
> +
- [ ] In your readme please explain how can a user clone and run your project

2021-11-16 20:24 UTC, GzimAsani commented on package.json
> +    "build": "webpack"
- [ ] Please add `start` and `dev` script and example:
 `"dev": "webpack --mode development",`
`"start": "webpack --config webpack.config.js --watch"`

2021-11-16 20:24 UTC, GzimAsani commented on src/index.html
> +<!DOCTYPE html>
- [ ] You should have a dist folder with the following files:
```
|- /dist
    |- bundle.js or be main.js
    |- index.html
```

2021-11-16 20:24 UTC, GzimAsani commented on src/index.html
> +<html lang="en">
- [ ] Html should look like this [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/images/leaderboard_wireframe.png) Currently I cant confirm this because I cannot run your project without adding the run script

2021-11-16 21:53 UTC, GintsM commented on src/index.html
> +<html lang="en">
It should be nothing in HTML, no script no styling links, cause we using webpack and maybe you noticed in file index.js line nr 1 import './style.css'; that is responsible for adding style to the page. even I don't have anything else in that file. So question what should I change here?

2021-11-16 21:53 UTC, GintsM commented on src/index.html
> +<!DOCTYPE html>
So I assume you couldn't install it in your local IDE. Because then you would see dist with HTML and main.js
Since I use gitignore and I choose Node models by default in gitignore - dist is part of those files. I can remove that, which I usually do when I want run a ready project.

2021-11-16 21:59 UTC, GintsM commented on package.json
> +    "build": "webpack"
I have mode development in webpack configuration
If you like when Your file is updating automatically you can use watcher. I don't and I will not implement or install it. No requirements for this.

2021-11-16 22:10 UTC, GintsM commented on README.md
> +
I will add a comment here for a quote - 'Please be reminded for next projects that the changes should be asked to be merged from the feature branch to the master branch', In this project, we are asked to follow Gitflow, which mean we should merge to development branch which is the made default branch for me, and in main we will merge only ready project. Don't you agree

2021-11-17 06:50 UTC, GintsM commented on README.md
> +
So You admit, your mistake, with removing the line from Required Changes comments, why don't you explain other comments?

2021-11-17 13:57 UTC, henatan99 requested changes
Hi @GintsM , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-17 13:57 UTC, henatan99 commented on src/index.html
> +<!DOCTYPE html>
I think you put the `dist` folder in gitignore and that is fine. I will leave this comment as optional.

2021-11-17 13:57 UTC, henatan99 commented on src/index.html
> +<html lang="en">
- [ ] I think you misunderstood the reviewer comment here. He said he couldn't run the app with the `npm start` command because the `start` key in the `scripts` of the package.json is missing. You should add this script as it is the project's requirement, so either take the previous reviewer's suggestion or another example code shown below. :pray: 

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --config webpack.config.js",
    "start": "webpack serve --open"
  },
```
![Screenshot from 2021-11-17 16-40-38](https://user-images.githubusercontent.com/64894927/142213765-44ef8ff6-0af6-44f9-b7f8-0e8ebbcd9626.png)


- [ ] In addition, `webpack-dev-server` should also be installed as a dev dependency. Kindly fix this issue too. :pray:

 
![Screenshot from 2021-11-17 16-40-53](https://user-images.githubusercontent.com/64894927/142213725-cd515cc1-41fd-487e-96c8-b903400d30ca.png)

2021-11-17 13:57 UTC, henatan99 commented on README.md
> +
- [ ] Kindly make changes in your readme as per the reviewer's comments. It is on of the general requirements to have a professional repo with a descriptive readme. :pray:

2021-11-19 06:07 UTC, D4nielJ approved these changes
## Hello @GintsM, 

# Congratulations! 🎉
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 06:18 UTC, merged